# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, song_id: int=None, album_id: int=None, merch_id: int=None, name: str=None, price: float=None, description: str=None, artist: str=None, colaborators: List[int]=None, release_date: datetime=None, duration: int=None, genre: str=None, cover: str=None, song_list: List[int]=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param song_id: The song_id of this Product.  # noqa: E501
        :type song_id: int
        :param album_id: The album_id of this Product.  # noqa: E501
        :type album_id: int
        :param merch_id: The merch_id of this Product.  # noqa: E501
        :type merch_id: int
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param price: The price of this Product.  # noqa: E501
        :type price: float
        :param description: The description of this Product.  # noqa: E501
        :type description: str
        :param artist: The artist of this Product.  # noqa: E501
        :type artist: str
        :param colaborators: The colaborators of this Product.  # noqa: E501
        :type colaborators: List[int]
        :param release_date: The release_date of this Product.  # noqa: E501
        :type release_date: datetime
        :param duration: The duration of this Product.  # noqa: E501
        :type duration: int
        :param genre: The genre of this Product.  # noqa: E501
        :type genre: str
        :param cover: The cover of this Product.  # noqa: E501
        :type cover: str
        :param song_list: The song_list of this Product.  # noqa: E501
        :type song_list: List[int]
        """
        self.swagger_types = {
            'song_id': int,
            'album_id': int,
            'merch_id': int,
            'name': str,
            'price': float,
            'description': str,
            'artist': str,
            'colaborators': List[int],
            'release_date': datetime,
            'duration': int,
            'genre': str,
            'cover': str,
            'song_list': List[int]
        }

        self.attribute_map = {
            'song_id': 'songId',
            'album_id': 'albumId',
            'merch_id': 'merchId',
            'name': 'name',
            'price': 'price',
            'description': 'description',
            'artist': 'artist',
            'colaborators': 'colaborators',
            'release_date': 'releaseDate',
            'duration': 'duration',
            'genre': 'genre',
            'cover': 'cover',
            'song_list': 'songList'
        }
        self._song_id = song_id
        self._album_id = album_id
        self._merch_id = merch_id
        self._name = name
        self._price = price
        self._description = description
        self._artist = artist
        self._colaborators = colaborators
        self._release_date = release_date
        self._duration = duration
        self._genre = genre
        self._cover = cover
        self._song_list = song_list

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def song_id(self) -> int:
        """Gets the song_id of this Product.

        ID of the Song (NULL if not song)  # noqa: E501

        :return: The song_id of this Product.
        :rtype: int
        """
        return self._song_id

    @song_id.setter
    def song_id(self, song_id: int):
        """Sets the song_id of this Product.

        ID of the Song (NULL if not song)  # noqa: E501

        :param song_id: The song_id of this Product.
        :type song_id: int
        """

        self._song_id = song_id

    @property
    def album_id(self) -> int:
        """Gets the album_id of this Product.

        ID of the Album (NULL if not album)  # noqa: E501

        :return: The album_id of this Product.
        :rtype: int
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: int):
        """Sets the album_id of this Product.

        ID of the Album (NULL if not album)  # noqa: E501

        :param album_id: The album_id of this Product.
        :type album_id: int
        """

        self._album_id = album_id

    @property
    def merch_id(self) -> int:
        """Gets the merch_id of this Product.

        ID of the Merch (NULL if not merch)  # noqa: E501

        :return: The merch_id of this Product.
        :rtype: int
        """
        return self._merch_id

    @merch_id.setter
    def merch_id(self, merch_id: int):
        """Sets the merch_id of this Product.

        ID of the Merch (NULL if not merch)  # noqa: E501

        :param merch_id: The merch_id of this Product.
        :type merch_id: int
        """

        self._merch_id = merch_id

    @property
    def name(self) -> str:
        """Gets the name of this Product.

        Name of the product  # noqa: E501

        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.

        Name of the product  # noqa: E501

        :param name: The name of this Product.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def price(self) -> float:
        """Gets the price of this Product.

        Price of the Song  # noqa: E501

        :return: The price of this Product.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Product.

        Price of the Song  # noqa: E501

        :param price: The price of this Product.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def description(self) -> str:
        """Gets the description of this Product.

        Description of the product  # noqa: E501

        :return: The description of this Product.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Product.

        Description of the product  # noqa: E501

        :param description: The description of this Product.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def artist(self) -> str:
        """Gets the artist of this Product.

        Name of the Artist that the product belongs to  # noqa: E501

        :return: The artist of this Product.
        :rtype: str
        """
        return self._artist

    @artist.setter
    def artist(self, artist: str):
        """Sets the artist of this Product.

        Name of the Artist that the product belongs to  # noqa: E501

        :param artist: The artist of this Product.
        :type artist: str
        """
        if artist is None:
            raise ValueError("Invalid value for `artist`, must not be `None`")  # noqa: E501

        self._artist = artist

    @property
    def colaborators(self) -> List[int]:
        """Gets the colaborators of this Product.

        List of Names of Artists who collaborated on the product (only song and album)  # noqa: E501

        :return: The colaborators of this Product.
        :rtype: List[int]
        """
        return self._colaborators

    @colaborators.setter
    def colaborators(self, colaborators: List[int]):
        """Sets the colaborators of this Product.

        List of Names of Artists who collaborated on the product (only song and album)  # noqa: E501

        :param colaborators: The colaborators of this Product.
        :type colaborators: List[int]
        """
        if colaborators is None:
            raise ValueError("Invalid value for `colaborators`, must not be `None`")  # noqa: E501

        self._colaborators = colaborators

    @property
    def release_date(self) -> datetime:
        """Gets the release_date of this Product.

        Date of release of the Song  # noqa: E501

        :return: The release_date of this Product.
        :rtype: datetime
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: datetime):
        """Sets the release_date of this Product.

        Date of release of the Song  # noqa: E501

        :param release_date: The release_date of this Product.
        :type release_date: datetime
        """

        self._release_date = release_date

    @property
    def duration(self) -> int:
        """Gets the duration of this Product.

        Duration of song in seconds (null if not a song)  # noqa: E501

        :return: The duration of this Product.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this Product.

        Duration of song in seconds (null if not a song)  # noqa: E501

        :param duration: The duration of this Product.
        :type duration: int
        """

        self._duration = duration

    @property
    def genre(self) -> str:
        """Gets the genre of this Product.

        Genre of a song (null if not song or album)  # noqa: E501

        :return: The genre of this Product.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Product.

        Genre of a song (null if not song or album)  # noqa: E501

        :param genre: The genre of this Product.
        :type genre: str
        """

        self._genre = genre

    @property
    def cover(self) -> str:
        """Gets the cover of this Product.

        base64 image of the cover  # noqa: E501

        :return: The cover of this Product.
        :rtype: str
        """
        return self._cover

    @cover.setter
    def cover(self, cover: str):
        """Sets the cover of this Product.

        base64 image of the cover  # noqa: E501

        :param cover: The cover of this Product.
        :type cover: str
        """
        if cover is None:
            raise ValueError("Invalid value for `cover`, must not be `None`")  # noqa: E501

        self._cover = cover

    @property
    def song_list(self) -> List[int]:
        """Gets the song_list of this Product.

        List of the names of songs that an Album has (null if not album)  # noqa: E501

        :return: The song_list of this Product.
        :rtype: List[int]
        """
        return self._song_list

    @song_list.setter
    def song_list(self, song_list: List[int]):
        """Sets the song_list of this Product.

        List of the names of songs that an Album has (null if not album)  # noqa: E501

        :param song_list: The song_list of this Product.
        :type song_list: List[int]
        """

        self._song_list = song_list
